# Generated by Django 2.2.6 on 2019-10-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextCorpora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_lemmatized', models.TextField()),
                ('text_tagged', models.TextField()),
            ],
            options={
                'db_table': 'text_corpora',
                'managed': False,
            },
        ),
    ]
